export const FETCH_CONVERSATION = "FETCH_CONVERSATION";
export const FETCH_CONVERSATION_ERROR = "FETCH_CONVERSATION_ERROR";
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";

export const FETCH_CHAT_CONVERSATION = "FETCH_CHAT_CONVERSATION";

export const FETCH_POST_FANPAGE_START = "FETCH_POST_FANPAGE_START";
export const FETCH_POST_FANPAGE_SUCCESS = "FETCH_POST_FANPAGE_SUCCESS";
export const FETCH_POST_FANPAGE_ERROR = "FETCH_POST_FANPAGE_ERROR";

export const FETCH_COMMENT_BYPOST = "FETCH_COMMENT_BYPOST";
export const FETCH_COMMENT_BYPOST_ERROR = "FETCH_COMMENT_BYPOST_ERROR";

export const SEND_FB_MESSAGE = "SEND_FB_MESSAGE";

export const GET_TWILIO_USER_START = "GET_TWILIO_USER_START";
export const GET_TWILIO_USER_SUCCESS = "GET_TWILIO_USER_SUCCESS";
export const GET_TWILIO_USER_ERROR = "GET_TWILIO_USER_ERROR";

export const GET_TWILIO_CHANNEL = "GET_TWILIO_CHANNEL";
export const GET_TWILIO_CHANNEL_ERROR = "GET_TWILIO_CHANNEL_ERROR";

export const FETCH_TWILIO_MESSAGES_START = "FETCH_TWILIO_MESSAGES_START";
export const FETCH_TWILIO_MESSAGES_SUCCESS = "FETCH_TWILIO_MESSAGES_SUCCESS";
export const FETCH_TWILIO_MESSAGES_ERROR = "FETCH_TWILIO_MESSAGES_ERROR";

export const SET_CURRENT_TAB = "SET_CURRENT_TAB";
export const SET_CURRENT_POST = "SET_CURRENT_POST";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";

export const SET_CURRENT_STATUS = "SET_CURRENT_STATUS";
export const SET_CURRENT_TYPE = "SET_CURRENT_TYPE";
